#!/usr/bin/env python3
import argparse
import time
import sys
from pathlib import Path
from datetime import datetime


from utils import die

def tzstring():
    delta = time.timezone
    dt = datetime.utcfromtimestamp(abs(delta))
    txt = dt.strftime('%H:%M')
    if delta > 0:
        return '-' + txt
    else:
        return '+' + txt


def get_date():
    now = datetime.now()
    return now.strftime('%Y-%m-%d %H:%M:%S') + ' ' + tzstring()


def set_field(lines, wanted_key, wanted_value):
    new_line = '{}: {}\n'.format(wanted_key, wanted_value)
    for idx, line in enumerate(lines):
        if ':' in line:
            key, _ = line.split(':', 1)
            if key.strip() == wanted_key:
                lines[idx] = new_line
                break
    else:
        lines.insert(0, new_line)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('path_to_index_md')
    args = parser.parse_args()

    path = Path(args.path_to_index_md)
    if not path.exists():
        die('ERROR: {} does not exist'.format(path))

    with path.open() as fp:
        lines = fp.readlines()

    set_field(lines, 'pub_date', get_date())
    set_field(lines, 'public', 'true')

    with path.open('w') as fp:
        fp.write(''.join(lines))

    return 0


if __name__ == '__main__':
    sys.exit(main())
# vi: ts=4 sw=4 et
