#!/usr/bin/env python3
import argparse
import os
import sys

import build
import config


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--clean', action='store_true', help='Clean')

    args = parser.parse_args()

    cfg = config.load()

    os.chdir(cfg['BLOG_DIR'])
    if args.clean:
        print('Cleaning previous build output')

    try:
        print('Building')
        build.build(clean=args.clean)
        build.serve()
    except KeyboardInterrupt:
        print()
    return 0


if __name__ == '__main__':
    sys.exit(main())
# vi: ts=4 sw=4 et
