#!/usr/bin/env python3
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from slugify import slugify

import config
from utils import die


def main():
    cfg = config.load()

    title = input('Title: ')
    summary = input('Summary: ')
    tags = input('Tags: ')

    slug = slugify(title)
    answer = input('Slug [{}]: '.format(slug))
    if answer:
        slug = answer

    year = datetime.now().year
    dirname = Path(cfg['BLOG_DIR']) / str(year) / slug
    filepath = dirname / 'index.md'

    if filepath.exists():
        die('ERROR: {} already exists'.format(filepath))

    if not dirname.exists():
        dirname.mkdir(parents=True)

    with filepath.open('w') as fp:
        print('public: false', file=fp)
        print('tags: [{}]'.format(tags), file=fp)
        print('title: {}'.format(title), file=fp)
        print('summary: |\n    {}\n'.format(summary), file=fp)

    print('Skeleton post created as {}'.format(filepath))

    answer = input('Edit now (y|N)? ')
    if answer.lower() == 'y':
        editor = cfg.get('BLOG_EDITOR', 'vim')
        subprocess.call([editor, str(filepath)])

    return 0


if __name__ == '__main__':
    sys.exit(main())
# vi: ts=4 sw=4 et
