#!/usr/bin/env python3
import argparse
import os
import re
import sys

from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("page")
    parser.add_argument("mastodon_link")

    args = parser.parse_args()

    content = Path(args.page).read_text()
    content, count = re.subn(
        "^mastodon:.*", f"mastodon: {args.mastodon_link}", content, flags=re.MULTILINE
    )
    if count != 1:
        sys.exit(f"Command made {count} replacement(s), expected 1")
    Path(args.page).write_text(content)

    return 0


if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
