#!/bin/bash
set -e

CONFIG=${RSTBLOG_TOOLS_CONFIG:-~/.config/rstblog-tools.conf}
echo "Loading config from $CONFIG"
. $CONFIG

cd $BLOG_DIR

echo -n "Title: "
read title

echo -n "Summary: "
read summary

echo -n "Tags: "
read tags

slug=$(echo $title | tr A-Z a-z | tr -- ' ' -)
echo -n "Slug [$slug]: "
read answer
if [ -n "$answer" ] ; then
    slug=$answer
fi

dir=$(date +%Y)/$slug
filename=$dir/index.md

if [ -e "$filename" ] ; then
    echo "ERROR: $filename already exists"
    exit 1
fi

mkdir -p $dir

cat > $filename <<EOF
public: false
tags: [$tags]
title: "$title"
summary: |
    $summary

EOF

echo "Skeleton post created as $filename"

echo -n "Edit now (y|N)? "
read answer
case "$answer" in
y|Y)
    ${EDITOR:-vim} "$filename"
    ;;
*)
    ;;
esac
