#!/bin/bash
set -e

CONFIG=${RSTBLOG_TOOLS_CONFIG:-~/.config/rstblog-tools.conf}
echo "Loading config from $CONFIG"
echo
. $CONFIG

cd $BLOG_DIR

move_from_drafts() {
    src_dir=$(dirname $src)
    dst_dir=$(date +%Y/%m/%d)
    echo "Moving $src from $src_dir to $dst_dir"
    mkdir -p $dst_dir
    git mv $src_dir $dst_dir/
}

has_field() {
    awk -F ':' '$0 == "" { exit 1 } $1 == "'$1'" { exit 0 }' $src
}

set_field() {
    key=$1
    value=$2
    if has_field $key ; then
        echo "Replacing existing value of '$key' with '$value'"
        sed -i "s/^$key:.*/$key: $value/" $src
    else
        echo "Adding new key '$key' with value '$value'"
        mv $src $src.old
        (
            echo "$key: $value"
            cat $src.old
        ) > $src
        rm $src.old
    fi
}

src=$1

if ! [ -e "$src" ] ; then
    echo "ERROR: $src does not exist"
    exit 1
fi

date="$(date +'%Y-%m-%d %H:%M:%S %:z')"

set_field pub_date "$date"
set_field public true

case "$src" in
drafts/*/index.md|*/drafts/*/index.md)
    move_from_drafts
    ;;
*)
    ;;
esac
